# Generated by Django 5.2.11 on 2026-03-02 21:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('address', models.CharField(max_length=300, verbose_name='Adres')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('website', models.URLField(blank=True, verbose_name='Strona WWW')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='Zdjęcie')),
                ('max_guests', models.PositiveIntegerField(default=100, verbose_name='Maks. liczba gości')),
                ('price_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena za osobę (PLN)')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Ogród / teren zewnętrzny')),
                ('has_dance_floor', models.BooleanField(default=False, verbose_name='Parkiet taneczny')),
                ('has_accommodation', models.BooleanField(default=False, verbose_name='Noclegi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Restauracja',
                'verbose_name_plural': 'Restauracje',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Wesele'), ('christening', 'Chrzciny'), ('communion', 'Komunia Święta')], max_length=20, verbose_name='Typ uroczystości')),
                ('event_date', models.DateField(verbose_name='Data uroczystości')),
                ('guest_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba gości')),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana'), ('completed', 'Zakończona')], default='pending', max_length=20, verbose_name='Status')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon kontaktowy')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail kontaktowy')),
                ('notes', models.TextField(blank=True, verbose_name='Dodatkowe uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.restaurant', verbose_name='Restauracja')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-event_date'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'event_date'), name='unique_restaurant_date')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Ocena')),
                ('comment', models.TextField(blank=True, verbose_name='Komentarz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.restaurant', verbose_name='Restauracja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
