# Generated by Django 5.2.11 on 2026-03-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternatywa dla przesłanego pliku', verbose_name='Link do zdjęcia'),
        ),
    ]
