# Generated by Django 6.0.2 on 2026-03-03 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_restaurant_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_owner', models.BooleanField(default=True, verbose_name='Główny właściciel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='bookings.restaurant', verbose_name='Restauracja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Właściciel restauracji',
                'verbose_name_plural': 'Właściciele restauracji',
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
