# Generated by Django 5.2.11 on 2026-03-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_restaurantowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wesele'), ('baptism', 'Chrzciny'), ('communion', 'Komunia Święta')], max_length=20, verbose_name='Typ uroczystości'),
        ),
        migrations.AlterField(
            model_name='restaurantowner',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='bookings.restaurant', verbose_name='Restauracja'),
        ),
    ]
