# Generated by Django 5.2.11 on 2026-03-03 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data kontaktu')),
                ('title', models.CharField(max_length=200, verbose_name='Temat / nazwa')),
                ('content', models.TextField(verbose_name='Treść notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='bookings.booking', verbose_name='Rezerwacja')),
            ],
            options={
                'verbose_name': 'Notatka CRM',
                'verbose_name_plural': 'Notatki CRM',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
