# Generated by Django 5.2.11 on 2026-03-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookingnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('appetizer', 'Przystawki'), ('soup', 'Zupy'), ('main', 'Główne danie'), ('dessert', 'Deser'), ('buffet', 'Bufet'), ('drink', 'Napoje')], max_length=20, verbose_name='Kategoria')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena (zł)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Pokaż na głównej stronie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='bookings.restaurant', verbose_name='Restauracja')),
            ],
            options={
                'verbose_name': 'Pozycja menu',
                'verbose_name_plural': 'Pozycje menu',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookingMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_selections', to='bookings.booking', verbose_name='Rezerwacja')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_selections', to='bookings.menuitem', verbose_name='Pozycja menu')),
            ],
            options={
                'verbose_name': 'Wybór menu',
                'verbose_name_plural': 'Wybory menu',
                'unique_together': {('booking', 'menu_item')},
            },
        ),
    ]
