# Generated by Django 5.2.11 on 2026-03-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_menuitem_bookingmenuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'Firma', 'verbose_name_plural': 'Firmy'},
        ),
        migrations.AlterModelOptions(
            name='restaurantowner',
            options={'verbose_name': 'Właściciel firmy', 'verbose_name_plural': 'Właściciele firm'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='attraction_type',
            field=models.CharField(blank=True, choices=[('photographer', 'Fotograf / Wideo'), ('photobooth', 'Fotobudka'), ('photo_wall', 'Ścianki do zdjęć'), ('animations', 'Animacje')], help_text='Wypełnij tylko dla typu Atrakcje', max_length=20, verbose_name='Rodzaj atrakcji'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_radius_km',
            field=models.PositiveIntegerField(default=10, help_text='Wypełnij tylko dla Cateringu', verbose_name='Promień dowozu (km)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='firm_type',
            field=models.CharField(choices=[('venue', 'Imprezy w lokalu'), ('catering', 'Catering z dowozem'), ('attraction', 'Atrakcje')], default='venue', max_length=20, verbose_name='Typ firmy'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wesele'), ('baptism', 'Chrzciny'), ('communion', 'Komunia Święta'), ('birthday', 'Urodziny'), ('integration', 'Impreza integracyjna'), ('corporate_xmas', 'Wigilia firmowa'), ('catering', 'Catering'), ('other', 'Inne')], max_length=20, verbose_name='Typ uroczystości'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.restaurant', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='bookings.restaurant', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='restaurantowner',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='bookings.restaurant', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.restaurant', verbose_name='Firma'),
        ),
    ]
