# Generated by Django 5.2.11 on 2026-03-03 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('image_url', models.URLField(blank=True, verbose_name='Link do zdjęcia')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena (zł)')),
                ('tag', models.CharField(choices=[('scianka', 'Ścianka'), ('tort', 'Tort'), ('fotograf', 'Fotograf'), ('wideo', 'Wideofilmowanie'), ('fotobudka', 'Fotobudka'), ('fontanna', 'Fontanna czekoladowa')], max_length=20, verbose_name='Tag')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_items', to='bookings.restaurant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Pozycja atrakcji',
                'verbose_name_plural': 'Pozycje atrakcji',
                'ordering': ['tag', 'order', 'name'],
            },
        ),
    ]
