# Generated by Django 5.2.11 on 2026-03-03 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_attractionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'Wesele'), ('baptism', 'Chrzciny'), ('communion', 'Komunia Święta'), ('birthday', 'Urodziny'), ('integration', 'Impreza integracyjna'), ('corporate_xmas', 'Wigilia firmowa'), ('catering', 'Catering'), ('other', 'Inne')], max_length=20, verbose_name='Typ uroczystości'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba gości'),
        ),
    ]
