# Generated by Django 5.2.11 on 2026-03-03 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_event_type_alter_booking_guest_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść wiadomości')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data wysłania')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='bookings.booking', verbose_name='Rezerwacja')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_messages', to=settings.AUTH_USER_MODEL, verbose_name='Nadawca')),
            ],
            options={
                'verbose_name': 'Wiadomość czatu',
                'verbose_name_plural': 'Wiadomości czatu',
                'ordering': ['created_at'],
            },
        ),
    ]
