# Generated by Django 5.2.11 on 2026-03-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_bookingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deal_agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Uzgodniona cena końcowa (zł)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deal_closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data zamknięcia dealu'),
        ),
        migrations.AddField(
            model_name='booking',
            name='deal_terms',
            field=models.TextField(blank=True, verbose_name='Warunki umowy / ustalenia'),
        ),
    ]
