# Generated by Django 5.2.11 on 2026-03-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_deal_agreed_price_booking_deal_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/gallery/', verbose_name='Plik zdjęcia')),
                ('image_url', models.URLField(blank=True, help_text='Alternatywa — URL zewnętrznego zdjęcia', verbose_name='Link do zdjęcia')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Podpis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='bookings.restaurant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Zdjęcie firmy',
                'verbose_name_plural': 'Zdjęcia firmy',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
