# Generated by Django 5.2.11 on 2026-03-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_restaurantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='welcome_message',
            field=models.TextField(blank=True, default='Dziękujemy za złożenie rezerwacji! 🎉 Cieszymy się, że wybraliście Państwo naszą firmę. Twoje zgłoszenie zostało przyjęte — skontaktujemy się z Tobą w ciągu 24 godzin, aby potwierdzić szczegóły i odpowiedzieć na ewentualne pytania. W razie pilnych spraw zadzwoń do nas. Do zobaczenia!', help_text='Wiadomość automatycznie wysyłana do klienta po złożeniu rezerwacji.', verbose_name='Wiadomość powitalna'),
        ),
    ]
