# Generated by Django 5.2.11 on 2026-03-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_restaurant_welcome_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantowner',
            options={'verbose_name': 'Członek firmy', 'verbose_name_plural': 'Członkowie firm'},
        ),
        migrations.RemoveField(
            model_name='restaurantowner',
            name='is_main_owner',
        ),
        migrations.AddField(
            model_name='restaurantowner',
            name='role',
            field=models.CharField(choices=[('owner', 'Właściciel'), ('worker', 'Pracownik')], default='owner', max_length=10, verbose_name='Rola'),
        ),
        migrations.AlterField(
            model_name='restaurantowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owners', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik'),
        ),
    ]
