# Generated by Django 5.2.11 on 2026-03-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='Poznań', max_length=100, verbose_name='Miasto'),
        ),
    ]
