# Generated by Django 5.2.11 on 2026-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_saved_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('appetizer', 'Przystawki'), ('soup', 'Zupy'), ('main', 'Główne danie'), ('dessert', 'Deser'), ('buffet', 'Bufet'), ('drink', 'Napoje')], max_length=20, verbose_name='Kategoria')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ostatnia cena (zl)')),
                ('usage_count', models.PositiveIntegerField(default=1, verbose_name='Ile razy uzyta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
            ],
            options={
                'verbose_name': 'Szablon pozycji menu',
                'verbose_name_plural': 'Szablony pozycji menu',
                'ordering': ['-usage_count', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
