# Generated by Django 5.2.11 on 2026-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_menu_item_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client_type',
            field=models.CharField(choices=[('private', 'Osoba prywatna'), ('company', 'Firma')], default='private', max_length=10, verbose_name='Typ klienta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adres firmy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nazwa firmy'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_nip',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIP'),
        ),
    ]
