# Generated by Django 5.2.11 on 2026-03-05 08:37

from django.db import migrations


def create_default_menus(apps, schema_editor):
    """
    Dla każdej restauracji posiadającej pozycje menu tworzy domyślne
    menu 'Menu główne' (is_active=True) i dowiązuje do niego
    istniejące pozycje.
    """
    Restaurant = apps.get_model("bookings", "Restaurant")
    Menu = apps.get_model("bookings", "Menu")
    MenuItem = apps.get_model("bookings", "MenuItem")

    restaurant_ids = (
        MenuItem.objects.values_list("restaurant_id", flat=True).distinct()
    )
    for rid in restaurant_ids:
        menu = Menu.objects.create(
            restaurant_id=rid,
            name="Menu główne",
            is_active=True,
        )
        MenuItem.objects.filter(restaurant_id=rid, menu__isnull=True).update(
            menu=menu,
        )


def reverse_default_menus(apps, schema_editor):
    MenuItem = apps.get_model("bookings", "MenuItem")
    Menu = apps.get_model("bookings", "Menu")
    MenuItem.objects.all().update(menu=None)
    Menu.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_menu_model'),
    ]

    operations = [
        migrations.RunPython(create_default_menus, reverse_default_menus),
    ]
