# Generated by Django 5.2.11 on 2026-03-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_menu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='fri_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Piątek do'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='fri_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Piątek od'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Poniedziałek do'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='mon_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Poniedziałek od'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Sobota do'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sat_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Sobota od'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Niedziela do'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sun_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Niedziela od'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Czwartek do'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='thu_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Czwartek od'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Wtorek do'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tue_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Wtorek od'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Środa do'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='wed_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Środa od'),
        ),
    ]
