# Generated by Django 5.2.11 on 2026-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina zakończenia'),
        ),
        migrations.AddField(
            model_name='booking',
            name='event_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina rozpoczęcia'),
        ),
    ]
