# Generated by Django 5.2.11 on 2026-03-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_booking_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='show_calendar',
            field=models.BooleanField(default=False, help_text='Wyświetla kalendarz z wolnymi/zajętymi terminami na stronie firmy (tylko Imprezy w lokalu).', verbose_name='Pokaż kalendarz dostępności'),
        ),
    ]
