# Generated by Django 5.2.11 on 2026-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0026_show_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='booking_slug',
            field=models.SlugField(blank=True, help_text='Unikalny adres formularza, np. mojevent.pl/rezerwacja/hotel-bomba', max_length=120, null=True, unique=True, verbose_name='Slug formularza'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='embed_enabled',
            field=models.BooleanField(default=False, verbose_name='Formularz zewnętrzny aktywny'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='scraped_css',
            field=models.TextField(blank=True, help_text='Automatycznie pobrane CSS/czcionki ze strony www restauracji.', verbose_name='Pobrane style CSS'),
        ),
    ]
