# Generated by Django 5.2.11 on 2026-03-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_embed_booking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
    ]
