# Generated by Django 5.2.11 on 2026-03-06 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0028_restaurant_facebook_url_restaurant_instagram_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Powód')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zablokowany dzień',
                'verbose_name_plural': 'Zablokowane dni',
                'ordering': ['date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_restaurant_date',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_events_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Ile rezerwacji może mieć jedno miejsce w jednym dniu.', verbose_name='Maks. wydarzeń dziennie'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='show_calendar',
            field=models.BooleanField(default=False, help_text='Wyświetla kalendarz z wolnymi/zajętymi terminami na stronie firmy.', verbose_name='Pokaż kalendarz dostępności'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('restaurant', 'event_date'), name='unique_active_restaurant_date'),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='bookings.restaurant', verbose_name='Firma'),
        ),
        migrations.AddConstraint(
            model_name='blockeddate',
            constraint=models.UniqueConstraint(fields=('restaurant', 'date'), name='unique_blocked_date'),
        ),
    ]
