# Generated by Django 5.2.11 on 2026-03-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0029_blockeddate_remove_booking_unique_restaurant_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Zadanie')),
                ('is_done', models.BooleanField(default=False, verbose_name='Wykonane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='bookings.booking', verbose_name='Rezerwacja')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
                'ordering': ['is_done', 'created_at'],
            },
        ),
    ]
