# Generated by Django 5.2.11 on 2026-03-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_bookingtodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='menu_type',
            field=models.CharField(blank=True, choices=[('detailed', 'Szczegółowy plan'), ('limited', 'Ograniczony Wybór'), ('buffet', 'Szwedzki Stół'), ('custom_mix', 'Własny Mix')], default='', max_length=20, verbose_name='Typ menu'),
        ),
        migrations.AddField(
            model_name='bookingmenuitem',
            name='guest_group',
            field=models.CharField(blank=True, default='', help_text='Np. Dorośli, Dzieci, Vege — używane w Własny mix.', max_length=50, verbose_name='Grupa gości'),
        ),
        migrations.AddField(
            model_name='bookingmenuitem',
            name='serving_order',
            field=models.PositiveIntegerField(default=0, help_text='Używane w trybie Szwedzki stół i Własny mix.', verbose_name='Kolejność serwowania'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='enabled_menu_types',
            field=models.JSONField(blank=True, default=list, help_text='Lista włączonych typów menu: detailed, limited, buffet, custom_mix', verbose_name='Dostępne typy menu'),
        ),
        migrations.CreateModel(
            name='BookingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa etapu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('serving_style', models.CharField(choices=[('for_all', 'Dla wszystkich (jedno danie)'), ('choice', 'Do wyboru (goście wybierają)'), ('buffet_style', 'Na stół (goście nakładają)'), ('continuous', 'Ciągłe serwowanie')], default='for_all', max_length=20, verbose_name='Sposób serwowania')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='bookings.booking', verbose_name='Rezerwacja')),
            ],
            options={
                'verbose_name': 'Etap menu (Mix)',
                'verbose_name_plural': 'Etapy menu (Mix)',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bookingmenuitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='bookings.bookingcourse', verbose_name='Danie / etap'),
        ),
    ]
