# Generated by Django 5.2.11 on 2026-03-07 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_booking_menu_type_bookingmenuitem_guest_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('appetizer', 'Przystawki'), ('soup', 'Zupy'), ('main', 'Główne danie'), ('dessert', 'Deser'), ('buffet', 'Bufet'), ('drink', 'Napoje')], max_length=20, verbose_name='Kategoria')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena (zł)')),
                ('source', models.CharField(choices=[('manual', 'Ręcznie'), ('excel', 'Import z Excel'), ('word', 'Import z Word'), ('text', 'Import z tekstu'), ('external', 'Zewnętrzna baza'), ('menu', 'Z istniejącego menu')], default='manual', max_length=20, verbose_name='Źródło')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='bookings.restaurant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Potrawa',
                'verbose_name_plural': 'Baza potraw',
                'ordering': ['category', 'name'],
                'unique_together': {('restaurant', 'category', 'name')},
            },
        ),
    ]
