# Generated by Django 5.2.11 on 2026-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_dish_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_catering_menu',
            field=models.BooleanField(default=False, help_text="Menu dla sekcji 'Catering na dowóz' (dotyczy firm venue z also_catering).", verbose_name='Menu cateringowe'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='also_catering',
            field=models.BooleanField(default=False, help_text="Zaznacz jeśli firma typu 'Imprezy w lokalu' oferuje również catering z dowozem.", verbose_name='Catering na dowóz'),
        ),
    ]
