# Generated by Django 5.2.11 on 2026-03-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0033_also_catering_and_catering_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, help_text='Opcjonalna nazwa rezerwacji / zamówienia.', max_length=200, verbose_name='Nazwa'),
        ),
    ]
